# Generated by Django 5.1.7 on 2025-06-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0002_session_end_time_alter_profile_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.DateTimeField(default='2025-06-11 12:00:00'),
            preserve_default=False,
        ),
    ]
