# Generated by Django 5.1.7 on 2025-06-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0004_alter_vote_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcard',
            name='icon_class',
            field=models.CharField(default='fas fa-circle', max_length=100),
        ),
        migrations.AddField(
            model_name='vote',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='color',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('amber', 'Amber'), ('green', 'Green')], max_length=10, null=True),
        ),
    ]
